# Autogenerated wrapper script for libdeflate_jll for aarch64-apple-darwin
export libdeflate

JLLWrappers.@generate_wrapper_header("libdeflate")
JLLWrappers.@declare_library_product(libdeflate, "@rpath/libdeflate.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libdeflate,
        "lib/libdeflate.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
